"""ConfigStore Protocol — single storage layer surface (D8).

Contract guarantees:
- list_categories: ordered by lower(name) ascending.
- list_runs(schedule_id): ordered by id descending.
- finish_run: updates the run row AND the parent schedule last_run_* fields.
- NotFoundError is raised on missing-id lookups (get_schedule, update_schedule,
  delete_schedule, finish_run, patch_query, deactivate_query, delete_query).
- ConflictError is raised on uniqueness / FK / General-category violations.
- delete_schedule cascades to runs; deactivate_query cascades to destinations.
- delete_query physically removes the query and cascades to destinations.
- seed_defaults is idempotent: empty-table guards prevent overwriting user rows.
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ConfigStore(Protocol):
    # ------------------------------------------------------------------
    # bootstrap
    # ------------------------------------------------------------------
    def ensure_schema(self) -> None: ...
    def seed_defaults(self) -> None: ...

    # ------------------------------------------------------------------
    # categories
    # ------------------------------------------------------------------
    def list_categories(self) -> list[dict]: ...
    def create_category(self, name: str, description: str | None = None) -> dict: ...
    def delete_category(self, category_id: int) -> None: ...

    # ------------------------------------------------------------------
    # queries
    # ------------------------------------------------------------------
    def list_queries(self) -> list[dict]: ...
    def get_query(self, name: str) -> dict | None: ...
    def upsert_query(self, row: dict) -> dict: ...
    def patch_query(self, name: str, patch: dict) -> dict: ...
    def deactivate_query(self, name: str) -> None: ...
    def delete_query(self, name: str) -> None: ...

    # ------------------------------------------------------------------
    # schedules / runs
    # ------------------------------------------------------------------
    def list_schedules(self) -> list[dict]: ...
    def get_schedule(self, schedule_id: int) -> dict | None: ...
    def create_schedule(self, row: dict) -> dict: ...
    def update_schedule(self, schedule_id: int, patch: dict) -> dict: ...
    def delete_schedule(self, schedule_id: int) -> None: ...
    def insert_run(self, run: dict) -> dict: ...
    def finish_run(self, run_id: int, result: dict) -> None: ...
    def list_runs(self, schedule_id: int) -> list[dict]: ...

    # ------------------------------------------------------------------
    # destinations
    # ------------------------------------------------------------------
    def list_destinations(self, query_name: str | None = None) -> list[dict]: ...
    def upsert_destination(self, dest: dict) -> dict: ...
    def mark_destination_stale(self, dest_id: int, error: str | None = None) -> None: ...
    def mark_destination_ok(self, dest_id: int, schema: dict | None = None) -> None: ...
    def seed_destinations_from_schedules(self) -> int: ...

    # ------------------------------------------------------------------
    # users
    # ------------------------------------------------------------------
    def list_users(self) -> list[dict]: ...
    def get_user_by_id(self, user_id: str) -> dict | None: ...
    def get_user_by_email(self, email: str) -> dict | None: ...
    def create_user(self, row: dict) -> dict: ...
    def update_user_password(self, user_id: str, password_hash: str) -> dict: ...
    def update_user(self, user_id: str, patch: dict) -> dict: ...
    def count_users(self) -> int: ...

    # ------------------------------------------------------------------
    # permissions
    # ------------------------------------------------------------------
    def list_permissions(self) -> list[dict]: ...
    def get_user_permissions(self, user_id: str) -> set[str]: ...
    def assign_user_permission(self, user_id: str, permission_id: str) -> None: ...
    def revoke_user_permission(self, user_id: str, permission_id: str) -> None: ...
    def seed_permission_defaults(self) -> None: ...
